[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/tmdb/:splat"
  status = 200
